import {
  Diamond02Icon,
  AtIcon,
  Building03Icon,
  StarIcon,
  FavouriteIcon,
  Medal04Icon,
  Crown03Icon,
  AiBeautifyIcon,
  CloudIcon,
  Saturn01Icon,
  SpaceshipIcon,
  FallingStarIcon,
  SpiralsIcon,
  Atom02Icon,
  MusicNote02Icon,
  HatGlassesIcon,
  Video02Icon,
  Home13Icon,
  PokemonIcon,
  GuitarIcon,
  HazeIcon,
  GemIcon,
  GameController03Icon,
  BoxingGloveIcon,
  BombIcon,
  ChessKnightIcon,
  Pizza01Icon,
  CookieIcon,
  Coffee02Icon,
  MountainIcon,
  TulipIcon,
  TreePalmIcon,
  Tree06Icon,
  Plug01Icon,
  Leaf04Icon,
  Leaf03Icon,
  FlameIcon,
  FlowerIcon,
  Target02Icon,
  TieIcon,
  UmbrellaIcon,
} from "@hugeicons/core-free-icons";

/** Fixed set of icons users can pick for a profile. Stored by name on `ProfileMeta.icon`. */
export const PROFILE_ICON_NAMES = [
  "Diamond02Icon",
  "AtIcon",
  "Building03Icon",
  "StarIcon",
  "FavouriteIcon",
  "Medal04Icon",
  "Crown03Icon",
  "AiBeautifyIcon",
  "CloudIcon",
  "Saturn01Icon",
  "SpaceshipIcon",
  "FallingStarIcon",
  "SpiralsIcon",
  "Atom02Icon",
  "MusicNote02Icon",
  "HatGlassesIcon",
  "Video02Icon",
  "Home13Icon",
  "PokemonIcon",
  "GuitarIcon",
  "HazeIcon",
  "GemIcon",
  "GameController03Icon",
  "BoxingGloveIcon",
  "BombIcon",
  "ChessKnightIcon",
  "Pizza01Icon",
  "CookieIcon",
  "Coffee02Icon",
  "MountainIcon",
  "TulipIcon",
  "TreePalmIcon",
  "Tree06Icon",
  "Plug01Icon",
  "Leaf04Icon",
  "Leaf03Icon",
  "FlameIcon",
  "FlowerIcon",
  "Target02Icon",
  "TieIcon",
  "UmbrellaIcon",
] as const;

export type ProfileIconName = (typeof PROFILE_ICON_NAMES)[number];

type IconType = typeof Diamond02Icon;

// `Record<ProfileIconName, IconType>` forces this object to stay in sync with
// PROFILE_ICON_NAMES above — missing/extra keys are a compile error.
export const PROFILE_ICON_MAP: Record<ProfileIconName, IconType> = {
  Diamond02Icon,
  AtIcon,
  Building03Icon,
  StarIcon,
  FavouriteIcon,
  Medal04Icon,
  Crown03Icon,
  AiBeautifyIcon,
  CloudIcon,
  Saturn01Icon,
  SpaceshipIcon,
  FallingStarIcon,
  SpiralsIcon,
  Atom02Icon,
  MusicNote02Icon,
  HatGlassesIcon,
  Video02Icon,
  Home13Icon,
  PokemonIcon,
  GuitarIcon,
  HazeIcon,
  GemIcon,
  GameController03Icon,
  BoxingGloveIcon,
  BombIcon,
  ChessKnightIcon,
  Pizza01Icon,
  CookieIcon,
  Coffee02Icon,
  MountainIcon,
  TulipIcon,
  TreePalmIcon,
  Tree06Icon,
  Plug01Icon,
  Leaf04Icon,
  Leaf03Icon,
  FlameIcon,
  FlowerIcon,
  Target02Icon,
  TieIcon,
  UmbrellaIcon,
};

/** Resolves a stored icon name to its hugeicons icon, or null if unset/unknown. */
export function getProfileIcon(name?: string | null): IconType | null {
  if (!name) return null;
  return PROFILE_ICON_MAP[name as ProfileIconName] ?? null;
}
